@AUTH_URL = http://127.0.0.1:3000

@API_VERSION = /api/v1

@REGISTER_ENDPOINT = /auth/register

@LOGIN_ENDPOINT = /auth/login

### INDEX
GET {{AUTH_URL}}/ HTTP/1.1


### REGISTER
POST {{AUTH_URL}}{{API_VERSION}}{{REGISTER_ENDPOINT}} HTTP/1.1
CONTENT-TYPE: application/json

{
    "email": "example@alumnos.ucn.cl",
    "role": "estudiante"
}

### LOGIN
POST {{AUTH_URL}}{{API_VERSION}}{{LOGIN_ENDPOINT}} HTTP/1.1
CONTENT-TYPE: application/json

{
    "idToken": "token",
    "userType": "estudiante"
}